### ISSUE TITLE
Breaks when .babelrc present from babel 6

### ISSUE THREAD

**Issue by zephraph** [pawelgalazka/runjs#10]
The babel runtime looks in the cwd for a `.babelrc` file. Unfortunately the rc files from babel 6 are not compatible with babel 5. This was a bit hard to detect because of how you're doing error handling in the bin file. 

```javascript
var call = require('../lib/index').call;
require("babel/register");
try {
    var runfile = require(process.cwd() + '/runfile');
    call(runfile, process.argv.slice(2));
} catch (e){
    // This doesn't print out a stack trace, difficult to debug
    // throw e.name + ':' + e.message;

    // Do this instead for a full stack trace
    throw e;
}
```

Solving this issue is a bit difficult. Ultimately it would be better if there was no direct dependency on Babel at all. With that being said, I do like being able to use ES6 without having to do anything special in the run file. 

Here's one option:
```javascript
var call = require('../lib/index').call;

try {
  require('babel/register');
} catch(babel5err) {
  // Babel 5 not present, try babel 6
  try {
    require('babel-register');
  } catch(babel6err) {
    // Babel not found, continue
  }
}
try {
    var runfile = require(process.cwd() + '/runfile');
    call(runfile, process.argv.slice(2));
} catch (e){
    throw e;
}
```

Essentially, you try to require each babel require hook. If both fail, you continue on your marry way. That way you can take out the dependency to babel but let people still use it to hook into their runscript without having to do anything weird in the runscript. 

The problem with this solution is it's pretty messy... and it's certainly not future proof. An alternative would be to give a way to specify what require hook should be called, presumably from the package.json. The good thing about this approach is that it opens up the door to use different types of transpilers. 

```javascript
// package.json
{
  "config": {
    "runjs": {
      "require-hook": "babel/register" // babel-register or any future thing could go here
     }
  }
}
```

```javascript
var config = require('pkg-config')('runjs');
var call = require('../lib/index').call;

try {
  if (config && config['require-hook']) {
    require(pkg.config.runjs['require-hook']);
  }
} catch (e) {
  // Require hook failed
}

try {
    var runfile = require(process.cwd() + '/runfile');
    call(runfile, process.argv.slice(2));
} catch (e){
    throw e;
}
```

I'm already this invested, expect a PR shortly.

**Comment by pawelgalazka** [comment]
The idea is pretty good, agree that I would not tied up user to an specific babel version, this is a good improvement. The thing which I would change in the second code example is to require babel6 version first (assumption that it will be more common case and we could reduce exception callbacks chain).

**Comment by zephraph** [comment]
What about the second solution? I feel like it's ultimately more robust. What if someone wanted to write their runfile in coffeescript? Or whatever new hotness comes out. I feel like that ultimately gives more power to the user.

**Comment by pawelgalazka** [comment]
I would combine them. If configuration is present then go with hook from configuration, if not then do the first part.

**Comment by zephraph** [comment]
Hmmm... all right.

**Comment by zephraph** [comment]
So there are actually two parts to this issue. 

- Part I: Fix pathing. #11 
- Path II: Add support for `require-hooks`.
