### ISSUE TITLE
running tasks in parallel 

### ISSUE THREAD

**Issue by ywauto83** [pawelgalazka/runjs#111]
it might be just a 101 question. I am wondering if running multi tasks in parallel is supported.

Thanks

**Comment by pawelgalazka** [comment]
You can make implementation of the task to work in async. For example `sh` function which executes shell command accepts  `async` option: https://github.com/pawelgalazka/tasksfile#shcmd-options

**Comment by dzaman** [comment]
While you can make multiple concurrent calls to `sh` with the `async` flag, I use [`concurrently`](https://www.npmjs.com/package/concurrently) for this:

```
const buildCommands = PROJECTS.map((project) => {
  return {
      name: project.name,
      command: `cd ${project.directory} && npx task build`,
      prefixColor: project.color,
  };
});
    
await concurrently(buildCommands);
```
