### ISSUE TITLE
Add task as a dedicated construct

### ISSUE THREAD

**Issue by zephraph** [pawelgalazka/runjs#14]
Currently a runfile just exports any tasks that it has directly from the runfile. That works, but it doesn't really scale well. Being that the setup for this project is reminiscent of gulp it might be good to look at what they do and why they do it. 

Generally any build process at scale is hard to manage in a single file. If you look at large gulp setups the gulpfile will just have a reference to `require-dir` and that will require some tasks directory with a bunch of build steps separated out into their own files. It keeps things easier to reason about and just cleaner over all. 

Gulp gets away with doing that because it stores all of the steps internally instead of having to do the export bit. Also, this approach just looks better in a non-es6 rendition. 

```javascript
import { run, task } from 'runjs';

task('build', () => { run('babel src/ --out-dir lib/') });
```

**Comment by pawelgalazka** [comment]
You can still put some stuff to external module right now and import it to the runfile, the thing is that you still need to explicitly export it if you want to have some task available from `run` command. But for internal use in the runfile you don't need to do that.

**Comment by pawelgalazka** [comment]
Some additional thoughts: The issue with `task` construct is that it's works kinda like a global variable, every module which imports `task` can throw something to `task` "bucket". It's a bit less explicit and clear in general I think. It raise additional questions/complexity:

- What if two modules will create task with the same name ?
- How can call the task inside another task ?
- How can I track where specific task is defined ?

Now everything works on pure es6 syntax and `runfile` is like an ordinary node.js module so you don't need to provide that additional clarification. Currently you can still modularize things, true you need to export task in runfile to make them visible from the `run` script but I think it is a good thing, make things more explicit and clear.

**Comment by zephraph** [comment]
The global concept is only mitigated in the current setup by the fact that you have to explicitly export any exposed task via the runfile. To answer your specific points:

- If a task is redeclared an exception would occur. 
- My initial thoughts are to connect a `task` function onto `run` -- `run.task('my-task')` 
- This one is a bit tricky. The only way that I currently know to do that would be to use the stacktrace API. That could be performed [manually](http://stackoverflow.com/a/13227808/2515020) or via a package like [caller](https://www.npmjs.com/package/caller).

You're right that the explicit nature of how it is right now makes it clear about your intent. I'd argue that it also increase the burden of maintenance though. I'd idealistically like to have the _ability_ to break down tasks into multiple files needing to edit the runfile every time I add a new task.

**Comment by pawelgalazka** [comment]
Closing this one for now. Final decision: going for more explicit nature of how things work

**Comment by fkrauthan** [comment]
@zephraph I created my own simple build system (a lot inspired by runjs) but with using a separate keyword to register tasks. That allows a lot more flexibility in terms of writing and organizing your build scripts. Feel free to take a look at https://github.com/fkrauthan/nss-run but be aware that that project is still in early stages.

**Comment by pawelgalazka** [comment]
RunJS v3.0.0 will introduce scaling support https://github.com/pawelgalazka/runjs/blob/v3.0.0-beta/README.md#scaling
