### ISSUE TITLE
Exclude lib/* from source

### ISSUE THREAD

**Issue by zephraph** [pawelgalazka/runjs#16]
`lib` is just the compiled version of the src. It doesn't need to be checked into the repository. Generally in a situation like this you'd use npm's `prepublish` step to build out. 

See an example: https://github.com/zephraph/postcss-remove-null/blob/master/package.json#L34

**Comment by pawelgalazka** [comment]
What if we want to allow users to install runjs from a github repository ?

**Comment by zephraph** [comment]
Hmm, I guess that's true. I didn't think about that use case.
