### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by karuppiah7890** [pawelgalazka/runjs#26]
It would be really good to have Contributing Guidelines (CONTRIBUTING.md), so that newbies like me can get our hands on the Project and see what it does and may be contribute to it :smile:

**Comment by pawelgalazka** [comment]
Thanks for suggestion! What informations would be particularly useful in your opinion ?

**Comment by karuppiah7890** [comment]
Well, things like 

1. Forking the repository in their GitHub account
2. Cloning the repo to local machine
3. `npm install`
4. `npm install -g . `
5. `npm link` to make development easier. 
6. Creating a separate branch for fix or feature.
7. Pushing to their GitHub repo
8. Creating a PR
9. Maintaining the Fork with the actual repo, for later development.

You can add or remove some stuff from the list. But it would be good to have them all. And you needn't type out stuff for everything. Some good links to guide the steps would be more than enough. Like, some of them are general and I see that most of these general steps are explained by [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp)'s Contributing Guidelines

**Comment by karuppiah7890** [comment]
The `npm link` thing, I learned from this https://developer.atlassian.com/blog/2015/11/scripting-with-node/

You could ask people to see that article to see how command line tools are made using npm.
