### ISSUE TITLE
"No runfile defined" error is not very neat

### ISSUE THREAD

**Issue by karuppiah7890** [pawelgalazka/runjs#27]
When I run the command `run` without defining the `runfile.js` or let's say if I made a typo and defined it as `runfil.js`, then an error message occurs and it is not very pleasing to see it. It says "cannot find module" for `runfile`. As a developer I should understand it. But it's better and neat to just say `No runfile.js defined` 

![error](https://cloud.githubusercontent.com/assets/12808424/19262946/6364333a-8fb7-11e6-9fd7-c59413c72a0e.png)

**Comment by karuppiah7890** [comment]
I want to fix this!

**Comment by pawelgalazka** [comment]
True, current error message can not look very clean in that case. As I'm assuming this could be the first error message which user can see, so we can do better. Good suggestion!

**Comment by karuppiah7890** [comment]
I actually put up a PR for this. Please take a look and suggest if it's good
