### ISSUE TITLE
Add descriptions to tasks

### ISSUE THREAD

**Issue by gunnx** [pawelgalazka/runjs#29]
Would be nice if you could add a longer description for each task, as you usually want to keep task names short. Also when you 'run' by itself and get a list of tasks it could print out the description there.

**Comment by karuppiah7890** [comment]
@pawelgalazka How does this format look ? For runfile.js, for describing tasks


```javascript

import {run} from 'runjs';

const task = {
    'create:component': {

      'description' : 'Creates a component',
      'run' : (name) => {

              }

    },
    'build:js': {

      'description' : 'Build Js',
      'run' : () => {
                  run('webpack -p --config config/webpack/prod.js --progress');
              }

    },
    'build:css': {

      'description' : 'Build CSS',
      'run' : () => {

              }

    },
    'build': {

      'description' : 'Build everything',
      'run' : () => {
                  task['build:js']();
                  task['build:css']();
              }
    }
};

export default task
```

**Comment by pawelgalazka** [comment]
There is one value in runjs which I would like to keep. Keeping things minimalistic. Task should be just a function and every exported function should be runnable. Thanks to this api is simple and clear. I think that construction above unnecessary overcomplicate things. Description could be a property on function object, so it can be easily added by ES7 decorator.

So I would see something like this:

```javascript
import { run } from 'runjs'

@description('some doc')
export function test () {

}

@description('some doc')
export function build () {

}
```

**Comment by karuppiah7890** [comment]
Yeah, I agree with your principle of keeping things minimalistic and simple. 
And Oh. Didn't know that's possible. I will check on it and try to implement it for the `run` command!

**Comment by pawelgalazka** [comment]
@karuppiah7890 BTW it's a bit of shame that decorators (https://babeljs.io/docs/plugins/transform-decorators/) works only for classes or class methods not for functions, because we could also do:

```javascript
@doc('Some description')
export function test () {

}
```

and `doc` decorator could adds a `doc` property to a function. Looks better but it's not possible currently.

**Comment by karuppiah7890** [comment]
@pawelgalazka Yeah, I saw this in my mail for the previous comment. I guess you then changed the comment to show how to add doc to a function.
