### ISSUE TITLE
Suggestion: Defining tasks in independent files

### ISSUE THREAD

**Issue by fkrauthan** [pawelgalazka/runjs#33]
Right now the runfile.js is mainly for defining all tasks in one file. This might work for very small projects but if you have a project with a lot files this gets out of hand very quickly. I created a small runfile.js that supports defining tasks in independent files. Not sure if you might wanna include this into the core project:

**The runfile.js**
```js
import requireDir from "require-dir";

const tasks = requireDir(`${__dirname}/tasks`, { recurse: true });

let runTasks = {};
Object.keys(tasks).forEach((file) => {
    // Ignore all files that start with _
    if (file.startsWith("_")) {
        return;
    }

    // Check if default is defined
    let taskDef = tasks[file];
    if (typeof taskDef.default !== "undefined") {
        taskDef = taskDef.default;
    }

    // Check if taskDef is a function
    if (typeof taskDef === "function") {
        taskDef = taskDef(runTasks);
    }

    // Merge tasks into big task object
    runTasks = Object.assign(runTasks, taskDef);
});

export default runTasks;
```

**Example Task 1: lint.js**
```js
import { run } from "runjs";

const tasks = {
    "lint:client": () => {
        run("eslint ./src/client/**/*.js");
    },
    "lint:server": () => {
        run("eslint ./src/server/**/*.js");
    },
    "lint:common": () => {
        run("eslint ./src/common/**/*.js");
    },
    "lint": () => {
        tasks["lint:client"]();
        tasks["lint:server"]();
        tasks["lint:common"]();
    }
};
export default tasks;
```

**Example Task 2: dev.js**
```js
export default (allTasks) => {
    const tasks = {
        "dev": () => {
            allTasks["lint"]();
            allTasks["webpack:development"]();
        },
    };
    return tasks;
};
```

As you can see this small code would allow already a very cool and extensible system even for large projects without sacrificing the simplicity of this project.

**Comment by pawelgalazka** [comment]
This is definitely the subject which needs to be covered in README (#34). My proposition would be to just make the solution more explicit than implicit. Better avoid `magic` behaviours with imports, as they can be confusing for other developers.

We could just re-export tasks which we need to use by `run` command. So for example:

*runfile.js*
```javascript
export { task1, task2 } from 'tasks/group1'
export { task3, task4 } from 'tasks/group2'
export { default as task5 } from 'tasks/bigtask'
```

and then you should be able to do `run task1` for example.
[re-exporting](http://jamesknelson.com/re-exporting-es6-modules/)

Obviously you need to re-export every task which you need but it's a good thing in my opinion. It's clear, explicit which tasks are available and it doesn't introduce any additional logic which developer needs to understand.

**Comment by pawelgalazka** [comment]
I forgot about the case when we have `something:something` naming for the tasks. In that case re-exporting syntax will not work but it can be easily and explicitly done also:

```javascript
import g1 from 'tasks/group1'
import g2 from 'tasks/group2'
import task5 from 'tasks/bigtask'

export default Object.assign({task5}, g1, g2)
```

**Comment by fkrauthan** [comment]
Hmm to be honest that makes it more complicated then having some "magic" happening in terms of auto detecting tasks.

**Comment by pawelgalazka** [comment]
For now I do not plan to introduce this change.
