### ISSUE TITLE
runfile.js at scale

### ISSUE THREAD

**Issue by pawelgalazka** [pawelgalazka/runjs#34]
We need a guide about: how to tackle large `runfile.js`
This needs to be covered in README.

Proposed idea: just use import and re-export needed group of tasks in `runfile.js` [re-exporting](http://jamesknelson.com/re-exporting-es6-modules/)

Related to #33

```javascript
export { task1, task2 } from 'tasks/group1'
export { task3, task4 } from 'tasks/group2'
export { default as task5 } from 'tasks/bigtask'
```

or for `something:something` tasks naming:

```javascript
import g1 from 'tasks/group1'
import g2 from 'tasks/group2'
import task5 from 'tasks/bigtask'

export default Object.assign({task5}, g1, g2)
```

**Comment by portenez** [comment]
this is what we're doing for modularization

**someTasks.js**
```javascript

import { run } from 'runjs'

export default {
  ['frontend:clean']: () => run('rm -rf node_modules'),
  ['frontend:install']: () => run('npm install')
}

```

**runfile.js**

```javascript
import someTasks from './someTasks.js'
import otherTasks from './otherTasks.js'

export default {
  ...someTasks, //es7
  ...otherTasks //es7
}

```

**Comment by pawelgalazka** [comment]
Awesome! Probably the best option so far

**Comment by portenez** [comment]
Just be aware that it requires `stage-0` babel preset. or at the very least the object spread.

**Comment by pawelgalazka** [comment]
Another option is to provide `combine` function we could additionally add some name spacing for tasks. For example:

```javascript
import { run, combine } from 'runjs'
import tasks1 from 'tasks1'
import tasks2 from 'tasks2'

export default combine({
  'frontend': tasks1,
  ...task2
})
```

```
run frontend:task-from-tasks1
run task-from-tasks2
```

**Comment by pawelgalazka** [comment]
or `namespace` function

```javascript
import { run, namespace } from 'runjs'
import tasks1 from 'tasks1'
import tasks2 from 'tasks2'

export default {
   ...namespace('frontend', tasks1)
   ...tasks2
}
```

**Comment by portenez** [comment]
could runjs create tasks groups by flattening the object structure on the fly?

```javascript

import tasks1 from 'tasks1'

export default {
  frontend: {
    ...tasks1
  }
}

```

would generate:

```bash

$run

frontend:task1
frontend:task2

**Comment by pawelgalazka** [comment]
Yup, also option worth considering

**Comment by pawelgalazka** [comment]
Last option will be introduced in v3.0.0 https://github.com/pawelgalazka/runjs/blob/v3.0.0-beta/README.md#scaling

**Comment by pawelgalazka** [comment]
Scaling solution introduced in runjs v3.0.0-beta.1
