### ISSUE TITLE
exit code is 0 when `task ${taskName} not found`

### ISSUE THREAD

**Issue by portenez** [pawelgalazka/runjs#35]
When executing `run task-that-does-not-exist`, and the task is not defined in the runfile, a message is printed but the exit code is 0. 

Can this be changed to some other exit code? 

Given that the current exit code is 0, build tools (e.g.: travis, jenkins, circleCi, etc) consider this step as successful and the build/pipeline breaks in unexpected ways.

**Comment by pawelgalazka** [comment]
Good point 👍 Yup, it will be fixed

**Comment by karuppiah7890** [comment]
Hey @pawelgalazka 

Is error code 1 fine for such errors ? Or are we gonna give different codes for different errors and then code them ?

**Comment by karuppiah7890** [comment]
Ok. The API tests failed when I tried `process.exit(1)`.
Looks like it abruptly exits from the API call, so the whole test stops. So to "gracefully" set an exit code as the nodejs docs say, I had to set `process.exitCode` and now the CLI works and the API tests are also passing!

**Comment by pawelgalazka** [comment]
I'm thinking about just throwing custom errors. Then we don't need to worry about managing `process.exit`. So we could catch let say `RunjsError`, print nice message for those (without the stack) and rethrow all other errors with stack.

**Comment by pawelgalazka** [comment]
Although we would still need to call `process.exit` in the `catch` section (in the run script). But at least we could avoid using `process` within the API and make API node independent.

**Comment by karuppiah7890** [comment]
Ah, okay

**Comment by portenez** [comment]
Does this means, it's fixed or it won't be fixed?

**Comment by pawelgalazka** [comment]
It's fixed by #39

**Comment by portenez** [comment]
Fantastic! thanks
