### ISSUE TITLE
`var output = run('some comand')` is null

### ISSUE THREAD

**Issue by portenez** [pawelgalazka/runjs#36]
You can capture the output of a command by using the async version of `run`. Is there any way we could have the same behavior for `run` without `async`? 

That is could `run` return the output of the message?

**Comment by pawelgalazka** [comment]
For sync behaviour run do `return chProcess.execSync(cmd, options);` where chProcess is `import chProcess from 'child_process';` from node. Will check this out.

**Comment by pawelgalazka** [comment]
Yup, I've got the issue. It's because for sync version option `stdio='inherit'` is set and that makes `execSync` return null since is piping output to parent process. Marking this as a bug, will try to find a solution

**Comment by pawelgalazka** [comment]
@portenez if you want a solution for now, you can `run('some command', {stdio: pipe})`. It will return the output but it will not pass it to the parent process thus not print it in the console.

**Comment by portenez** [comment]
K, thanks! I'm going to try it soon.

**Comment by portenez** [comment]
It worked with the `{ stdio: 'pipe' }` option

**Comment by pawelgalazka** [comment]
Fixed by runjs v3.0.0-beta.1
