### ISSUE TITLE
Allow run targets to be generators

### ISSUE THREAD

**Issue by portenez** [pawelgalazka/runjs#42]
May I suggest an enhancement?

```Story
As a developer using RunJs
I want to provide generators to RunJs
So that we more easily code heavily async targets
```

```Gherkin
Given I define a generator `function* generator(...args)`
When I define a target `['theBestTarget']: ...args => generator(args)`
Then RunJs should automatically wrap it to a promise, or yield the iterator.
```

We find ourselves wrapping our generators in a promise all the time. 

Given that RunJS also runs with babel, RunJS could also support async wait natively. Or, is this already supported?

**Comment by pawelgalazka** [comment]
Yeah... I know about this issue and I actually I tried to support async/await earlier but it turns out more complicated than I thought. Don't remember the reason exactly. Overall it is in a plan but not with hight priority.

**Comment by pawelgalazka** [comment]
@portenez With https://github.com/pawelgalazka/runjs/pull/61 support for async/await arrived. It's within `4.0.0` version. Closing this one then.

**Comment by portenez** [comment]
Cool, dzieki
