### ISSUE TITLE
Sub called tasks with chokidar don't work as expected.

### ISSUE THREAD

**Issue by nverba** [pawelgalazka/runjs#46]
Since the 3.0 update, I can no longer get chokidar to work in sub tasks. Either as a chokidar-cli command called with run, or by requiring chokidar directly in node. 

`chokidar './src/files/**/*.js' -c "run reload"`

or 

```
chokidar.watch('./src/files/**/*.js', {}).on('all', (event, path) => {
  console.log('reloading'')
  run(`reload`);
});
```

**Comment by pawelgalazka** [comment]
Any errors ?

**Comment by pawelgalazka** [comment]
Can you task `reload` directly as a function:
```javascript
chokidar.watch('./src/files/**/*.js', {}).on('all', (event, path) => {
  console.log('reloading'')
  reload() // or task['reload']() depending on your runfile.js
});
```

**Comment by pawelgalazka** [comment]
@nverba I've checked chokidar with runjs `3.0.0` and everything works perfectly fine. Looks like your task call in a callback is incorrect. So construction should be something like this:

```javascript
import { run } from 'runjs'
import chokidar from 'chokidar'

export function watch () {
  chokidar.watch('.', {}).on('all', (event, path) => {
    console.log('WATCH', event, path)
    reload()
  });
}

export function reload () {
  console.log('reloading')
}
```

**Comment by nverba** [comment]
Thank you for the assist. 
I would often call run tasks from within run tasks. This worked without issue in previous versions of runjs, and seemed like a simple (read: lazy) way of building up/chaining complex build steps.

I see now that this was a bad pattern. Having spent yesterday refactoring our build process, I'm happy to say your advice has not only fixed the issue I was having, but the code quality is looking much better now too.

Thanks again.

**Comment by pawelgalazka** [comment]
@nverba very cool 👍  happy to help
