### ISSUE TITLE
"Ask" function

### ISSUE THREAD

**Issue by pawelgalazka** [pawelgalazka/runjs#5]

**Comment by zephraph** [comment]
What does this mean exactly?

**Comment by pawelgalazka** [comment]
It's about introducing some basic mechanism for gathering informations from the user (prompting) which can be encountered in `npm init` for example or yeoman. Ideally it should be able to work nicely with `template` method.

**Comment by zephraph** [comment]
hmmm, that would be nice. Yeoman uses inquirer.js.

**Comment by pawelgalazka** [comment]
I would see something like this:

```javascript
import {ask, generate} from 'runjs';

export function createFile(){
  generate('file.tmp.js', 'file.js', ask({
    name: 'Component name',
    description: 'Description of the component'
  }));
}
```

**Comment by pawelgalazka** [comment]
or even further:

```javascript
import {ask, generate} from 'runjs';

export function createFile(){
  generate('file.tmp.js', `${ask('File name')}.js`, ask({
    name: 'Component name',
    description: 'Description of the component'
  }));
}
```

**Comment by zephraph** [comment]
What would this look like in the users prompt?

**Comment by pawelgalazka** [comment]
Simple prompt like in `npm init` for now without default values.

**Comment by zephraph** [comment]
I'm assuming you'd want to just use vanilla node for this? https://nodejs.org/api/readline.html#readline_rl_question_query_callback

**Comment by pawelgalazka** [comment]
That is the plan, although that library has a asynchronous character and I think that synchronous approach would be enough for that case and the side effects (code) would be less complex (don't need callbacks there).

**Comment by zephraph** [comment]
Right. I was just trying to point out a native node solution. I haven't looked into any libraries to do that instead of inquirer.js.
