### ISSUE TITLE
Support dashed arguments

### ISSUE THREAD

**Issue by bmcallis** [pawelgalazka/runjs#50]
I'd like to be able to supply arguments with dashes in them to a runjs task so I can use the same arguments as the commands I'm calling.

So something like this

```
export const build = (options={}) => {
  if (options['hide-modules'] {
    run('webpack -p --config config/webpack/prod.js --progress --hide-modules');
  } else {
    run('webpack -p --config config/webpack/prod.js --progress');
  }
}
```
Then calling `run build --hide-modules` would run webpack with the `--hide-modules` flag.

What happens today is that modules is treated as the first argument and hide is passed as an option. Which causes issues since I don't actually have any arguments for my tasks. 

I opened [PR 49](https://github.com/pawelgalazka/runjs/pull/49) to address this.

**Comment by pawelgalazka** [comment]
Solved by #49
