### ISSUE TITLE
generate fails for templates with lodash operators

### ISSUE THREAD

**Issue by ChisholmKyle** [pawelgalazka/runjs#52]
I tried to use `generate` with a template that had an iteration `<% _.forEach(myobj.some_array, function(var) { %> ...` which failed because the lodash template function requires the object as an input to build as well as execute the template. 
I was able to apply the template successfully using lodash templates separately.
I made a pull request #51 to solve the problem, but it's untested.

**Comment by pawelgalazka** [comment]
@ChisholmKyle change seems to be unnecessary, I've tested `generate` with using a loop, and it works perfectly fine.

`template.tpl`:
```
users: <% users.forEach(user => {%><%= user %> <%}) %>
```

`runfile.js`:
```javascript
import { generate } from 'runjs'

export function testgenerate () {
  generate('./template.tpl', './template.txt', {users: ['Pawel', 'John']})
}
```

`template.txt` (results):
```
users: Pawel John 
```
