### ISSUE TITLE
Npm script options

### ISSUE THREAD

**Issue by mrdbarker** [pawelgalazka/runjs#59]
More of a question at this point, but is there a way to create npm scripts that don't have any options specified, and then pass those through to runjs via the command line. For example:

```
"scripts": {
    "test": "run tasks:test"
}
```

And then in the command line:

`npm run test --flag=true`.

In this case, could `this.options` in the `test` task have `{ flag: true }` set?

Ideally, I don't want to have runjs installed globally and would instead prefer if npm scripts were the entry point that simply called runjs.

Thanks very much.

**Comment by pawelgalazka** [comment]
@mrdbarker What about `npm run test -- --flag=true` ?

**Comment by mrdbarker** [comment]
Ace, thanks for the help (in a crazy fast time, too!). I had put the `--` in the task itself 😢
