### ISSUE TITLE
nodemon command not found

### ISSUE THREAD

**Issue by hong-duc** [pawelgalazka/runjs#63]
I follow the example, create project install nodemon with `yarn install nodemon`, install run-cli with 'yarn global runjs-cli', create runfile.js and copy content in the readme.

When I type `run dev`, It throw error `nodemon command not found`
I am using linux mint

**Comment by pawelgalazka** [comment]
@hong-duc That's serious bug which you found. Somehow it passed through tests and it must be introduced with version `4.1.0` when some refactor took place in failing area. Need to fix the tests for that. Construction of `PATH` which includes `node_modules/.bin` was broken. 

Anyway, implementation is already fixed, you can install new version of runjs `4.1.3`. Update of `runjs-cli` is not needed.
