### ISSUE TITLE
Any plans to add auto-complete ability to the cli? 

### ISSUE THREAD

**Issue by cainus** [pawelgalazka/runjs#64]
This is one thing `make` still has on `run`.  I can type `make [tab]` and it gives me a list of possible targets.  Something like https://github.com/f/omelette could help there I think.

(Great utility BTW.  Nice work!)

**Comment by pawelgalazka** [comment]
I've tried `omelette` but I couldn't make it work, maybe I will give it another look

**Comment by pawelgalazka** [comment]
@cainus good news! 😄 autocompletion landed in runjs `4.3.0` https://github.com/pawelgalazka/runjs#autocompletion . It is in experimental phase though.

**Comment by tenorok** [comment]
Is there this possibility in the `task`-command?
