### ISSUE TITLE
Using runjs as a generic task runner

### ISSUE THREAD

**Issue by BinaryBen** [pawelgalazka/runjs#72]
Not sure if bug report or feature request...

Is it possible to use a global installation of runjs without having to type: `npm install runjs` in every directory I want to use a runfile? When I am trying currently, it gives the following:

```bash
ben$ run test
RunJS not found. Do "npm install runjs --save-dev" or "yarn add --dev runjs" first.
```

It would be great to use runjs globally (i.e., having run `npm install -g runjs`) without assuming it's a node project, or that it has a package.json file and node modules associated with it. That way I could use it like a Makefile and string shell commands together.

**Comment by pawelgalazka** [comment]
Unfortunately it is not possible currently to do that. Even if you do `npm install -g runjs-cli`, every `run` call will look for a local `runjs` installation. This is intentionally as it was not planned to call `runfile.js` tasks outside of node js project.

**Comment by BinaryBen** [comment]
Are there any strong reasons to not use it outside of a node project? If not, would you accept someone else writing the code for runjs-cli so that it can be used outside of a node project then?

Just curious about the thinking behind this, but obviously it's your project to do with what you want! 👍

**Comment by pawelgalazka** [comment]
@BinaryBen One of the risks working `runjs-cli` separately from `runjs` version in node project is `runjs` versions conflict. What if user has different version of `runjs-cli` and `runjs` which are incompatible ? That's why `runjs-cli` uses `runjs` implementation from local project. This solves that issues. Of course one way to go around this, is using local implementation if exist and using general global installation if not. But that may be unnecessary complication.

**Comment by pawelgalazka** [comment]
@BinaryBen if you are interested `runjs` with version < 4.0.0 , works the way you want.

**Comment by BinaryBen** [comment]
Hey @pawelgalazka, thanks I'll have a look at the older version and see if it has most of the same features for general use :)

> Of course one way to go around this, is using local implementation if exist and using global implementation if local does not exist. But that may be unnecessary complication.

I personally think this should be an option - especially if called from `$ run task` (i.e., with runjs-cli installed) in the shell. Something I noticed the other day was that runjs-cli and `npx run task` doesn't work in nested directories – it throws `RunJS not found. Do "npm install runjs --save-dev" or "yarn add --dev runjs" first.` as I assume it's only looking for node_modules in the current directory).

I imagine that could be considered a bug? Unless it is expected that users *have* to call the module from the project root, but that seems needlessly inconvenient to me. So if that was changed to search for a runfile.js and the runjs module in higher directories, it could then makes sense to fallback to a global installation if it exists as well (assuming it finds a runfile.js but no node_modules/runjs directory...?).

**Comment by BinaryBen** [comment]
I would agree though it make sense to be ready to commit to syntax for the runfiles to avoid incompatibilities and conflicts between versions. Otherwise you could provide an option to set a flag to allow runjs-cli to use a global install of runjs, caveat emptor?

```bash
run --force task [arguments]
```

**Comment by pawelgalazka** [comment]
@BinaryBen I think we could improve how `runjs-cli` loads local `runjs` as you mentioned. Currently it's hardcoded to `require('./node_modules/runjs/lib/script.js')`, probably we could change the way how we load it. Happy to take a look at PR.

**Comment by BinaryBen** [comment]
Alright cheers for considering it, hopefully I'll get a chance to look at it over the next fortnight. :)
