### ISSUE TITLE
Expose SilentLogger?

### ISSUE THREAD

**Issue by ivan-kleshnin** [pawelgalazka/runjs#78]
Current way to disable logging:

```js
class SilentLogger {
  title() {}
  log() {}
  warning() {}
  error() {}
}

// Write link
run(`mkdir -p '${P.dir(link)}'`, {}, someOptions.verbose ? undefined : new SilentLogger())
run(`ln -sFf '${P.resolve(path)}' '${link}'`, {}, someOptions.verbose ? undefined : new SilentLogger())
```

Too much effort, especially with file splitting. Additional import or declaration of `SilentLogger` per file...

One option to simplify this is to expose `SilentLogger` currently used internally:

```js
import {run, SilentLogger} from "runjs"
```

**Comment by pawelgalazka** [comment]
Have you tried `{stdio: 'ignore'}` option ? For example:
```js
run('mkdir somedir', {stdio: 'ignore'})
```

**Comment by pawelgalazka** [comment]
I think you should be able to do:

```js
import { SilentLogger } from "runjs/common"
```

**Comment by ivan-kleshnin** [comment]
I've tried first one, but was too lazy to look into `node_modules` :)
Will you accept a PR to mention this in docs?
