### ISSUE TITLE
Support handlebars templates

### ISSUE THREAD

**Issue by AdamHess** [pawelgalazka/runjs#8]
lodash templating is atypical for most developers to use. Your project also only uses lodash for templating, even though lodash has a myriad of other functionality, at it's core it wasn't designed for templating.

**Comment by pawelgalazka** [comment]
One of the values which I'm trying to keep for runjs is minimalism and shallow learning curve. Decision for lodash was that does not add much of template/language specific syntax, it makes use of js already meeting most of the needs which we expect from the templating language. Are there any other specific advantages of handlebars which should be considered ?

**Comment by AdamHess** [comment]
handlebar templates are prefered because they are generally easier to read. (though this could be subjective) 


<%=variable%>  looks too much like an HTML tag, harder to read and is more inline with a C# webforms template 

{{variable}} is much easier to read and clearly separates itself from HTML tags. It's also generally more prefered in the nodejs community. 

Also the idea behind handlebars is to encourage **logicless** templating as much as you can.

**Comment by pawelgalazka** [comment]
I found an issue with handlebars, this template is in conflict with some ReactJS syntax:

```javascript
var template = Handlebars.compile("<b style={{color: 'pink'}}>abc</b>");
console.log(template());
```

this is causing compilation error and it is allowed syntax in React/JSX.

**Comment by AdamHess** [comment]
1. ReactJs is not production ready its still in 0.x.x versioning it's so
volatile that it wouldn't be prudent to build on top of it.
2. React must be transpiled first before it can interact with any other
javascript language/tools.

**Comment by pawelgalazka** [comment]
1. True, versioning of react is in 0.x.x but it is already used on production by many. Also not only react is in conflict but angular templates/components too.

2. I think that's not the point. Purpose of `template()` util is for scaffolding. User should be able to scaffold for example react (in jsx) or angular components which should be easy to read later.

It looks like lodash templates are not in conflict with other js tools which could take part in scaffolding which is a winning thing here to support them by default.

Although using different template system is not a problem. `template()` function is very simple and custom version of it can be easily made by users.

**Comment by zephraph** [comment]
This could feasibly be made a bit more robust. You could have the option to register a generator that has the same method signature as the `generate` method has right now. Default it to the lodash method. 

I'm not sure how worth while it is though. Like @pawelgalazka said, the method itself is very, very simple and could be written standalone.

**Comment by pawelgalazka** [comment]
I'm closing this down. To sum up with a decision, support for handlebars is not planned.
