### ISSUE TITLE
Allow `task:subtask` and also `task`

### ISSUE THREAD

**Issue by vjpr** [pawelgalazka/runjs#81]
A convention where `task:index` would be run when running `task` would be good.

That is, there should be a default task that runs for a namespace.

**Comment by pawelgalazka** [comment]
You can already do that, check https://github.com/pawelgalazka/runjs#namespacing

**Comment by BinaryBen** [comment]
Additionally, it would be good if the help summary could just list the main functions.

So if I have `watch:css`, `watch:html`, and `watch:index` (currently I'm using :all but can adapt if this is implemented), I would just see as an example:

```bash
$ run
Available tasks:
  install
  watch
  deploy
```

I would then expect to see all of the subtasks listed if I entered `run watch --help` though.

**Comment by tenorok** [comment]
It's possible already now:
```js
function task() {}
task.subtask = function() {};

module.exports = {
    task
};
```

**Comment by pawelgalazka** [comment]
Yes, example above should work ^ Although code may look like a bit wonky

**Comment by pawelgalazka** [comment]
Closing this one as this is possible already

**Comment by tenorok** [comment]
There is only one moment that with above approach will not work autocompletion.

**Comment by mszczepanczyk** [comment]
> Closing this one as this is possible already

@pawelgalazka are you referring to the code shared by @tenorok? Tasks declared as such are not listed by helper.

```ts
const { run } = require('tasksfile')
const { cli } = require('tasksfile/lib/script')

function build () {
  run('echo build')
}

build.dev = function () {
  run('echo build:dev')
}

cli({
  build
})
```

```
$ npx task
Available tasks:
build

Type "task [taskname] --help" to get more info if available.
```

**Comment by tenorok** [comment]
@mszczepanczyk you're right, but how we can see in the [sources](https://github.com/pawelgalazka/cli/blob/31290eaca07037fae12642ea847e3a9c4b8789a9/src/middlewares/commandFinder.ts#L23-L34) the next example will work:

```js
const { sh, cli } = require('tasksfile');

const build = {
    default() {
        sh('echo build');
    },
    dev() {
        sh('echo build:dev');
    },
};

cli({
    build,
});
```

```
› task --help

Commands:

build
build:dev
```
