### ISSUE TITLE
Specify path to a runfile.js?

### ISSUE THREAD

**Issue by slavafomin** [pawelgalazka/runjs#84]
Hello!

Thank you for this great module!

However, is there a way to specify path to a `runfile.js`?

Thanks!

**Comment by pawelgalazka** [comment]
@slavafomin Yes there is. Take a look at this example: https://github.com/pawelgalazka/runjs#typescript

**Comment by slavafomin** [comment]
Thanks, but what if I don't want to specify it in `package.json`? I want to pass it as a CLI argument.

**Comment by pawelgalazka** [comment]
Then it's not really possible
