### ISSUE TITLE
wish: option to decamelize task names

### ISSUE THREAD

**Issue by markstos** [pawelgalazka/runjs#87]
It's great that tasks are just exported methods. 

However, using camelcase in CLI commands feels out of place. Most CLI commands in most tools are still allow lower case.

I'm interested having the option to publish and use "decamelized" versions of my task names.

With Gulp, it seems you have to explicitly give your tasks alternate names if you don't like using cameCase on the CLI, but I think there's a better way.

Using modules like [decamelize](https://www.npmjs.com/package/decamelize) and [camelcase](https://www.npmjs.com/package/camelcase), we could display versions with dashes in help and on the CLI, while using camelCase for function names, where dashes would illegal. For example:

```javascript
module.exports = {
    watchFrontend = () => { ... }
}
```

```shell
run watch-frontend
```

**Comment by markstos** [comment]
I looked into this more and found that nothing stops you from using keys with dashes in them in `module.exports`. It's exporting an Object and Objects have always allowed strings as as keys.

Here's a bit of code that shows automatically setting up module.exports with dashes in the task names, and also demonstrates that dashes in function names can work fine as long as the functions are object properties.

```
"use strict"
const _ = require('lodash')
const decamelize = require('decamelize')

const before = {
  'someName':  () => { console.log(1) },
  'otherFunc' : () => { console.log(2) } 
}

// Simulate creating a `module.exports` that decamelizes all the task names
let yourExports = {};
 _.forIn(before, (v, k) => {
    yourExports[decamelize(k,'-')] = v;  
})

console.log(yourExports)

const FE =  {};

// Test assigning a method to an object key with dashs
FE['dash-test'] = () => { console.log("inside dash-test") }

// Test calling with a function with dashes in the name.
FE['dash-test']()
```

Even with that finding, I think it would still be nice to have an easy way to reference functions with dashes used instead of camelCase.

This could possibly be solved with documentation instead of code.

**Comment by pawelgalazka** [comment]
Exactly, as mentioned above, nothing stops user from defining tasks with hyphens style.
Changing `camelCalse` to `hyphen-style` would unnecessary complicate code and introduce some edge cases, for example:

```js
module.exports = {
  watchFrontend: () => {},
  'watch-frontend': () => {}
}
```

what should we do in this case ?

Unnecessary complication and it downgrades transparency what actually is called.
