### ISSUE TITLE
Better exceptions handling in the runfile

### ISSUE THREAD

**Issue by pawelgalazka** [pawelgalazka/runjs#9]
Currently when some error happens in the runfile feedback about the error is not really informative.

**Comment by zephraph** [comment]
Is this the error that you're talking about? Because it certainly isn't informative and I have no idea what's breaking. 

```
/Users/<user>/git/<project>/node_modules/runjs/bin/run.js:9
    throw e.name + ':' + e.message;
    ^
TypeError:Cannot read property 'error' of undefined
```

**Comment by pawelgalazka** [comment]
Yes that's the thing

**Comment by zephraph** [comment]
#18 tries to do this in the simplest way possible.
