### ISSUE TITLE
docs: Table of Contents link to "options" is broken.

### ISSUE THREAD

**Issue by markstos** [pawelgalazka/runjs#91]
Table of Contents link to "Options" is broken.

Also, it should be documented why "this" should be passed to options() and noted that passing "this" is optional. 

Thanks.

**Comment by pawelgalazka** [comment]
I fixed the link in the docs.
Considering `runjs` will be moving to this api: https://github.com/pawelgalazka/runjs/issues/77 further description about `this` won't be necessary
