### ISSUE TITLE
wish: elide long "run" command output

### ISSUE THREAD

**Issue by markstos** [pawelgalazka/runjs#92]
I have a `run` command with a dynamically generated argument list that current passes about 900 arguments to a command. This creates *REALLY* noisy output from `runjs`. 

I propose that the `run()` output be elided after 100 characters. That is, if the string is > 100 characters log, truncate it back to 97 characters and append "..." to the output. 

The tiny `lodash.truncate()` module handles exactly this task.

https://www.npmjs.com/package/lodash.truncate

**Comment by pawelgalazka** [comment]
I would argue that this feature is not really essential inside `runjs` and it can be easily "solved" currently by providing custom logger to `run` function, which is its 3rd argument:

```js
const { SilentLogger } = require('runjs/lib/common')
const { run } = require('runjs')
const truncate = require('lodash.truncate')

class MyLogger extends SilentLogger {
  title: truncate
}

run('some command', {}, new SilentLogger())
run('some command', {}, new MyLogger())
```

**Comment by markstos** [comment]
Essential? No.

A better default user experience: Yes.
